import { createClient } from '@supabase/supabase-js';

// Import the client from the auto-generated file instead of creating a new one
import { supabase as autoGeneratedClient } from '@/integrations/supabase/client';

// Export the auto-generated client
export const supabase = autoGeneratedClient;