// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpqucimxaxtnzjxkrlwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwcXVjaW14YXh0bnpqeGtybHd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM3NjE1NDgsImV4cCI6MjA0OTMzNzU0OH0.o7wqetMZEo10mjiObolHgRwXvXF9V6FQtnfWo1-Yqdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);